### ISSUE TITLE
X-SAMPA characters using < or > not rendering or parsing properly in Moodle IPA filter.

### ISSUE THREAD

**Issue by anderhaff** [kwiliarty/moodle-filter_ipa#1]
It appears that X-SAMPA characters that have a < or > don't get properly converted into IPA (at, least, on our local installation).

Here's an example (pasted as image since the actual text is truncated):
![screen shot 2015-08-24 at 12 55 00 pm](https://cloud.githubusercontent.com/assets/7968310/9446371/5f3b9472-4a5f-11e5-85cf-334c8f02b371.png)

Renders on the page as:
![screen shot 2015-08-24 at 12 39 25 pm](https://cloud.githubusercontent.com/assets/7968310/9445996/2c739bc2-4a5d-11e5-9b56-9b0c0bd5cab4.png)

The above X-SAMPA code renders correctly using this tool: http://aveneca.com/xipa.html

This seems to happen both in Atto or TinyMCE. The IPA filter is at the top of the list, so it should be rendering first.

What could be causing this behavior?

**Comment by kwiliarty** [comment]
I'll investigate.

**Comment by kwiliarty** [comment]
Yep, a bug. That's me failing to decode HTML entities. Fix on the way.
